#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Use local commitlint binary to avoid npx fetching remote packages
if [ -x "./node_modules/.bin/commitlint" ]; then
	./node_modules/.bin/commitlint --edit "$1"
else
	npx --no -- commitlint --edit "$1"
fi
